if(NOT DEFINED PROJECT_IS_TOP_LEVEL)
  string(COMPARE EQUAL "${CMAKE_SOURCE_DIR}" "${PROJECT_SOURCE_DIR}" PROJECT_IS_TOP_LEVEL)
endif()

if(PROJECT_IS_TOP_LEVEL)
  set(PROJECT_IS_TOP_LEVEL_OPT ON)
else()
  set(PROJECT_IS_TOP_LEVEL_OPT OFF)
endif()
