name: MacOS

on:
  push:
    branches:
      - develop
      - master
      - release/*
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.compiler.name }} ${{ matrix.build_type }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13]
        build_type: [Release, Debug]
        compiler: [
          {name: GCC 12, cc: gcc-12, cxx: g++-12, brew_ver: gcc@12, package: false},
          {name: GCC 14, cc: gcc-14, cxx: g++-14, brew_ver: gcc@14, package: true},
          {name: Clang 14, cc: clang, cxx: clang++, package: true}
        ]

    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
      - name: (Optional) Compiler instalation
        if: ${{ matrix.os == 'macos-13' && startsWith(matrix.compiler.cc, 'gcc') }}
        run: |
          if ! command -v ${{ matrix.compiler.cc }} &> /dev/null
          then
            brew install ${{ matrix.compiler.brew_ver }}
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg
          vcpkgGitCommitId: '782ccc18d8b819cdef6794a6c03eb3d9f7cd04aa'

      - name: CMake configuration
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: Building
        run: cmake --build build --config ${{ matrix.build_type }} -j 8
      - name: Testing
        run: ctest --test-dir build --output-on-failure --timeout 15


      # Prepare & upload binaries
      - name: Prepare binaries
        if: matrix.compiler.package && github.event_name != 'pull_request'
        run: cmake --install build --prefix install --config ${{ matrix.build_type }}
        continue-on-error: true
      - name: Upload binaries as artifact
        if: matrix.compiler.package && github.event_name != 'pull_request' && success()
        uses: actions/upload-artifact@v4
        with:
          name: libbase-${{ github.ref_name }}-${{ matrix.compiler.cc }}-${{ matrix.build_type }}-${{ matrix.os }}-x64.zip
          path: install
          retention-days: 7
        continue-on-error: true
