name: MacOS

on:
  push:
    branches:
      - develop
      - master
      - release/*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.compiler.name }} ${{ matrix.build_type }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13]
        build_type: [Release, Debug]
        compiler: [
          {name: GCC 12, cc: gcc-12, cxx: g++-12, brew_ver: gcc@12},
          {name: GCC 14, cc: gcc-14, cxx: g++-14, brew_ver: gcc@14},
          {name: Clang 14, cc: clang, cxx: clang++}
        ]

    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
      - name: (Optional) Compiler instalation
        if: ${{ matrix.os == 'macos-13' && startsWith(matrix.compiler.cc, 'gcc') }}
        run: |
          if ! command -v ${{ matrix.compiler.cc }} &> /dev/null
          then
            brew install ${{ matrix.compiler.brew_ver }}
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg
          vcpkgGitCommitId: '782ccc18d8b819cdef6794a6c03eb3d9f7cd04aa'

      - name: CMake configuration
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: Building
        run: cmake --build build -j 8
      - name: Testing
        run: ctest --test-dir build --output-on-failure
